runtime: nodejs18  # Asegúrate de usar una versión compatible de Node.js

handlers:

- url: /
  static_files: dist/pcr/browser/index.html
  upload: dist/pcr/browser/index.html

- url: /(.*)
  static_files: dist/pcr/browser/\1
  upload: dist/pcr/browser/.*
