runtime: nodejs18 

handlers:

- url: /
  static_files: dist/pcr/browser/index.html
  upload: dist/pcr/browser/index.html

- url: /(.*)
  static_files: dist/pcr/browser/\1
  upload: dist/pcr/browser/.*
