runtime: python39

handlers:
  # Maneja la URL raíz y sirve el archivo index.html como página principal
  - url: /
    static_files: dist/pcr/index.html
    upload: dist/pcr/index.html

  # Maneja todos los archivos estáticos desde el directorio dist/pcr
  - url: /(.*)
    static_files: dist/pcr/\1
    upload: dist/pcr/(.*)
